development: &non_production_settings
  site_url: http://localhost:3000
  site_name: Patchwork
  admin_email: yhirai@pira.jp
  
test:
  <<: *non_production_settings

staging:
  site_url: http://staging.example.com
  site_name: Patchwork
  admin_email: yhirai@pira.jp
  
production:
  site_url: http://www.example.com
  site_name: Patchwork
  admin_email: yhirai@pira.jp
